MMTEngineTest: main.cpp
	g++ -g -o MMTEngineTest main.cpp \
	\
	util.cpp \
	\
	StandardAtmosphere1962/TFAtm62.cpp \
	\
	MMTMassAndMotorProperties/MMTMassAndMotorProperties.cpp \
	\
	MMTGuidance/MMTGuidance.cpp